Fix specific versions
Specific versions, such as 17.0.6, stopped working after the commit
mentioned below with the following error message:

     Checking known assets (os=linux, arch=x64, version=17.0.6)...
    Error: Unsupported version for platform (os=linux, arch=x64, version=17.0.6)!

Fixes: 0871d332bcc6 ("Use generated assets file")